email: kiankyars@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: auto
  header_pages:
    - pages/about.md
    - pages/now.md
    - pages/projects.md
    - pages/doomscrolling.md
    - pages/weekly-victories.md
    - pages/blog.md