email: kiankyars@gmail.com

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - pages/about.md
  - pages/now.md
  - pages/projects.md
  - pages/doomscrolling.md
  - pages/weekly-victories.md
  - pages/blog.md