title: Kian Kyars
email: kiankyars@gmail.com
description: Kian Kyars's personal blog
baseurl: "/"
url: "https://kiankyars.github.io"
twitter_username: neuralkian
github_username: kiankyars

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: auto
