title: Kian Kyars
email: kiankyars@gmail.com
description: Kian Kyars's personal blog
baseurl: "/"
url: "https://kiankyars.github.io"
twitter_username: neuralkian
github_username: kiankyars

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post
